#! ---------------------------------------------------------------
#! WARNING THERE ARE MANY
#! CHINGLISH IN THIS YAML
#! ---------------------------------------------------------------

# 0:white-theme
# A special theme.

WHITE: false

# 1:menu
# Don't add root.
# "吐槽" is on "topbar".
# Please edit it (index.html or not) if there's something wrong.

menu:
  Archives: archives/index.html
  tags: tags/index.html
  categories: categories/index.html
  about: somepage/about/index.html
  留言: somepage/chat/index.html
  友链: somepage/link/index.html
  项目: somepage/projects/index.html
  yznazo: yznazo/index.html

吐槽: 
  url: somepage/吐槽/index.html

# About toolbar menu, please edit source code.

# 2:article settings
#
# Please add the following at the head of the article if you need:
#
# ---
# discomments: true                # Used to disable comments in this article or page.
# bgimg: /path/to/your/pic.img     # Set backgound img for post card.
# top: [number]                    # Set post display order.
# height: [number]                 # If backgound img is set, it set post card's height.
# disfa: true                      # Used to disable Font Awesome in post card.
# faname: [string]                 # Set Font Awesome in post card. Default "fa-user".
# ---
#
# Note: "bgimg" conflicts with "faname", and "bgimg" has higher priority.

# 3:menu-icon
# "icon" from http://www.fontawesome.com.cn .
# "吐槽" is on "topbar".

icon:
  Archives: fa-archive
  tags: fa-tags
  categories: fa-navicon
  about: fa-user
  留言: fa-commenting
  友链: fa-link
  项目: fa-cog
  yznazo: fa-gamepad
  吐槽: fa-bell-o

# 4:comments
# Comments will be opened on pages other than those containing "discomments: true".

comments:
  # LiveRe comments system
  # You can get your uid from https://livere.com/insight/myCode (General web site)
  livere:
    enable: false
    uid: MTAyMC80Njg5MS8yMzM5Mg==
  # gitalk comments system
  # see: https://github.com/gitalk/gitalk
  # setting: please edit ./layout/_partial/comments.ejs
  gitalk:
    enable: true

# 5:responsive
#If the screen width is less than this value, the page layout will change to suit different screens.The unit is px.

responsive:
  dividing_1: 1200 # hide toolbar
  dividing_2: 800 # hide sidebar
  dividing_3: 480 # change topbar and margin/padding

# 6:display site warning

site_warning:
  enable: false
  text: '<i class="fa fa-check-circle-o" aria-hidden="true"></i> Happy new year!'
  type: danger   # You can set it danger|warning|info|success , or default.
  bgcolor: ce3027  # If it's set,the color will be changed.
  color:

# 7:footer

footer:
  left: 'Copyright ©2018-2020 yz-hs. All rights reserved.'
  right: 'Theme is <a href="https://github.com/yz-hs/yzpheme">yzpheme</a>,by yz-hs.'

# 8:copyright

copyright:
  enable: post  # You can set it all|post|disable , or default(disable).
                # all: displayed at the end of every page.
                # post: only displayed at the end of every post.
                
  statement: '本博客所有文章除特别声明外，均允许规范转载。转载请注明出处！当然也可对文章出处进行考证，在下方评论区评论！'

# 9:others

# post excerpt
post_excerpt:
  mode: excerpt        # You can set it excerpt|noexcerpt , or default(excerpt).
                       # excerpt: if a post has "<!--more-->",display it.
                       # onexcerpt: all posts are considered as having no excerpt.

  ifdefault: false     # if it is true,then if a post has no "<!--more-->",display "post_default_excerpt".
                       # else display part of content.

  display: text        # You can set it html|text , or default(text).
                       # html: HTML tags will remain.
                       # text: HTML tags will not remain.

  post_default_excerpt: '<i class="fa fa-warning" aria-hidden="true"></i> 本文章无可提供的摘要qwq。'
  length_excerpt: 100   # The length of "part of content".Default 30.

  # !WARNING!: If display part of content and HTML tags remain, there will be some wrong. 

# short description
short_des: "A cute OIer"

# avatar
avatar:
  url: /img/new-avatar.jpg

# font-family
font_family: Saira, DengXian, sans-serif;

# colored-eggs
colored_eggs:
  santa: true
  reverse: true

# END:note

# (1) Mathjax is turned on globally.
# (2) "RSS地址" requires `hexo-generator-feed` plugin to use. Please run `npm install hexo-generator-feed`. 
# (3) "wordcount" requires `hexo-wordcount` plugin to use. Please run `npm i hexo-wordcount --save`.
# (4) "文章置顶" 事实上是按照文章的 top 值排序，并加上 "置顶" 标签。请参看 ./_doc/top.md .
# (5) "blog-encrypt" requires `hexo-blog-encrypt` plugin to use. Please run `npm install --save hexo-blog-encrypt`.
# (6) Setting your 'path-to-your-blog/_config.yml'.per_page 0 is recommended.







#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

menu_name:
  Archives:
    name: Archives
  tags:
    name: tags
  categories:
    name: categories
  about:
    name: about
  留言:
    name: 留言
  友链:
    name: 友链
  项目:
    name: 项目
  yznazo:
    name: yznazo