#! ---------------------------------------------------------------
#! WARNING THERE ARE MANY
#! CHINGLISH IN THIS YAML
#! ---------------------------------------------------------------

# 0:white-theme
# A special theme.

WHITE:  # WHITE | MAIN (default MAIN)

# 1:menu
# Don't add root.
# Please edit it (index.html or not) if there's something wrong.

Menu:
  Archives: archives/index.html
  Tags: tags/index.html
  Categories: categories/index.html
  About: somepage/about/index.html
  Message_board: somepage/chat/index.html
  Links: somepage/link/index.html
  Projects: somepage/projects/index.html

Topbar: somepage/吐槽/index.html

# About toolbar menu, please edit source code.

# 2:article settings
#
# Please add the following at the head of the article if you need:
#
# ---
# discomments: true                # Used to disable comments in this article or page.
# bgimg: /path/to/your/pic.img     # Set backgound img for post card.
# top: [number]                    # Set post display order.
# height: [number]                 # If backgound img is set, it set post card's height.
# color: [string]                  # Set post card's context color. Default "#fff" or $text-color.
# disfa: true                      # Used to disable Font Awesome in post card.
# faname: [string]                 # Set Font Awesome in post card. Default "fa-file-text".
# tocd: [number]                   # Set toc depth.
# author: [string]                 # Set author. Default config_.yml.
# ---
#
# Note: "bgimg" conflicts with "faname", and "bgimg" has higher priority.

# 3:menu-icon
# "icon" from http://www.fontawesome.com.cn .
# "吐槽" is on "topbar".

icon:
  Archives: fa-archive
  Tags: fa-tags
  Categories: fa-navicon
  About: fa-user
  Message_board: fa-commenting
  Links: fa-link
  Projects: fa-cog
  Topbar: fa-bell-o

# 4:comments
# Comments will be opened on pages other than those containing "discomments: true".

comments:
  # LiveRe comments system
  # You can get your uid from https://livere.com/insight/myCode (General web site)
  livere:
    enable: false
    uid: 
  # gitalk comments system
  # see: https://github.com/gitalk/gitalk
  gitalk:
    enable: true
    clientID: "''"
    clientSecret: "''"
    repo: "''"
    owner: "''"
    admin: "['']"

# 5:responsive
#If the screen width is less than this value, the page layout will change to suit different screens.The unit is px.

responsive: # It influences "responsive" and width of body.
  # normal  (PC)
  dividing_1: 1230
  # thiner  (PC)
  dividing_2: 970
  # toolbar (Pad)
  dividing_3: 750
  # sidebar (PE)

# 6:display site warning

site_warning:
  enable: all   # You can set it none|root|all , or default(none).
  text: '<i class="fa fa-volume-up" aria-hidden="true"></i> 欢迎来到 cieu 的博客！希望我们能相互交流，共同进步～'
  type: warning  # You can set it danger|warning|info|success , or default.
  bgcolor:       # If it's set,the color will be changed.
  color:

# 7:footer
# You can't edit it.qwq.

footer:
  left: 'Copyright ©2019-2021 cieu. All rights reserved.'
  right: 'Theme is <a href="https://github.com/yz-hs/cieuka">cieuka</a>,by cieu.'

# 8:copyright

copyright:
  enable: post  # You can set it all|post|disable , or default(disable).
                # all: displayed at the end of every page.
                # post: only displayed at the end of every post.
                
  statement: '本博客所有文章除特别声明外，均允许规范转载。转载请注明出处！当然也可对文章出处进行考证，在下方评论区评论！'



# 9:post excerpt
post_excerpt:
  mode: excerpt        # You can set it excerpt|noexcerpt , or default(excerpt).
                       # excerpt: if a post has "<!--more-->",display it.
                       # noexcerpt: all posts are considered as having no excerpt.

  ifdefault: false     # if it is true,then if a post has no "<!--more-->",display "post_default_excerpt".
                       # else display part of content.

  display: html        # You can set it html|text , or default(text).
                       # html: HTML tags will remain.(Only a post has "<!--more-->")
                       # text: HTML tags will not remain.

  post_default_excerpt: '<i class="fa fa-warning" aria-hidden="true"></i> 本文章无可提供的摘要qwq。'
  length_excerpt: 150   # The length of "part of content".Default 30.

  # !WARNING!: If display part of content and HTML tags remain, there will be some wrong. 

# 10:tag-cloud color

tag_cloud:
  from: "#fff"
  to: "#fff"

# 11:others

# site=title
title: cieu's Blog

# short description
short_des: "A cute OIer"

# avatar
avatar:
  url: /img/new-avatar.jpg

# font,only one
font: Montserrat

# colored-eggs
colored_eggs:
  santa: true
  reverse: true

# color schemes
# value: white | trans | night | std | red | none (default std; "none" is very spacial)
color_schemes: trans

# spacial
# value: none | grayscale | invert  (default: none)
# 注：   没有  |  白事用   | 阴间特效
spacial:

# background image url

bg-url: /img/new-bgp.jpg

# http://momentjs.cn/docs/#/parsing/string-format/
time_format: "YYYY-MM-DD, HH:mm:ss"

# opacity 0~1
opacity: 1

# END:note

# (1) Mathjax is turned on globally.
# (2) "RSS地址" requires `hexo-generator-feed` plugin to use. Please run `npm install hexo-generator-feed`. 
# (3) "wordcount" requires `hexo-wordcount` plugin to use. Please run `npm i hexo-wordcount --save`.
# (4) "文章置顶" 事实上是按照文章的 top 值排序，并加上 "置顶" 标签。请参看 ./_doc/top.md .
# (5) "blog-encrypt" requires `hexo-blog-encrypt` plugin to use. Please run `npm install --save hexo-blog-encrypt`.
# (6) Setting your 'path-to-your-blog/_config.yml'.per_page 0 is recommended.
# (7) hexo-neat   hexo-generator-sitemap   ...
# (8) If you want to set Tags/Categories page, please set these pages' type. (type: Tags/Categories)






#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

# Nothing.