# 1:menu
# Don't add "/"(root).
# "留言" is on "topbar".

menu:
  Archives: archives/index.html
  tags: tags/index.html
  categories: categories/index.html
  about: somepage/about/index.html
  留言: somepage/talk/index.html
  友链: somepage/友链/index.html
  项目: somepage/projects/index.html
  yznazo: yznazo/index.html

# 2:article settings
#
# Please add the following at the head of the article if you need:
#
# ---
# discomments: true  #There is only "true". Used to disable comments in this article or page.
# ---
#

# 3:avatar

avatar:
  url: /img/avatar.jpg

# 4:menu-icon
# "icon" from http://www.fontawesome.com.cn .
# "留言" is on "topbar".

icon:
  Archives: fa-archive
  tags: fa-tags
  categories: fa-navicon
  about: fa-user
  留言: fa-bell-o
  友链: fa-link
  项目: fa-cog
  yznazo: fa-gamepad

# 5:comments
# LiveRe comments system
# You can get your uid from https://livere.com/insight/myCode (General web site)
comments:
  enable: true # Comments will be opened on pages other than those containing "discomments: true".
  livere_uid: MTAyMC80Njg5MS8yMzM5Mg==

# 6:responsive page
responsive:
  dividing: 1000 #If the screen width is less than this value, the page layout will change to suit different screens.The unit is px.

# 7：short description

short_des: "A cute OIer"

# END:note

# (1) Mathjax is turned on globally.
# (2) "RSS地址" requires `hexo-generator-feed` plugin to use. Please run `npm install hexo-generator-feed`. 